### ISSUE TITLE
Unclear how to use Token authentication

### ISSUE THREAD

**Issue by voros1** [dxFeed/dxfeed-graal-net-api#32]
It is unclear how to use the standard Token based authentication as described here:
https://kb.dxfeed.com/en/data-access/token-based-authorization.html
with this API.

**Comment by stdcion** [comment]
@voros1 1 hello!

The authorization token must be passed as part of the address, e.g.
`"address:port[login=entitle:token]"`

This address can be specified when creating an endpoint:
`var endpoint = DXEndpoint.Create().Connect("address:port[login=entitle:token]");`

or save in `dxfeed.properties` file:
```
# Connection address for an endpoint with role Feed and OnDemandFeed.
dxfeed.address=address:port[login=entitle:token]
```
and use default application-wide singleton instance
`var sub = DXFeed.GetInstance().CreateSubscription(typeof(Quote));`

For a simple check, you can use [DxFeed.Graal.Net.Tools](https://github.com/dxFeed/dxfeed-graal-net-api/releases/tag/0.2.1)
`./DxFeed.Graal.Net.Tools connect "address:port[login=entitle:token]" Quote AAPL`



Best regards,
dxFeed APIs Team

**Comment by voros1** [comment]
Thank you, that resolves this issue.
