### ISSUE TITLE
Setting authentication token

### ISSUE THREAD

**Issue by jsuttonnc** [dxFeed/dxfeed-graal-net-api#35]
I've been digging through the examples and the documentation and I cannot find how to set the authentication token at my brokerage is providing me.  How does one go about doing that?

**Comment by jsuttonnc** [comment]
never mind....I think I got it.  Found how to set it in the Program.cs file

**Comment by stdcion** [comment]
@jsuttonnc  1 hello!

The authorization token must be passed as part of the address, e.g.
`"address:port[login=entitle:token]"`

This address can be specified when creating an endpoint:
`var endpoint = DXEndpoint.Create().Connect("address:port[login=entitle:token]");`

or save in `dxfeed.properties` file:
```
# Connection address for an endpoint with role Feed and OnDemandFeed.
dxfeed.address=address:port[login=entitle:token]
```
and use default application-wide singleton instance
`var sub = DXFeed.GetInstance().CreateSubscription(typeof(Quote));`

For a simple check, you can use [DxFeed.Graal.Net.Tools](https://github.com/dxFeed/dxfeed-graal-net-api/releases/tag/0.2.1)
`./DxFeed.Graal.Net.Tools connect "address:port[login=entitle:token]" Quote AAPL`



Best regards,
dxFeed APIs Team
