### ISSUE TITLE
Authentication without a Port

### ISSUE THREAD

**Issue by voros1** [dxFeed/dxfeed-graal-net-api#41]
Hello,

What authentication string would I use for a dxfeed URL in this format:
wss://foo.dxfeed.com/bar
The auth code appears to crash because it is trying to find a Port:
One or more errors occurred. (
Java Class: com.devexperts.qd.qtp.AddressSyntaxException
Java Message: Port number format error in ...

Thanks.

**Comment by stdcion** [comment]
Hello,

Unfortunately, at this time, this library does not support websocket transport.
But there is now active development of a connector (on Java side) that will allow connection to dxLink services via websocket.

Best regards,
dxFeed APIs Team

**Comment by voros1** [comment]
OK, thanks.  I've moved on and am using the POCO classes from this project, ie Quote, Trade etc in combination with custom DXLink websocket code.

**Comment by stdcion** [comment]
Oh, that sounds good. We considered this option as well, but decided that it would be more universal to solve this task once on the java side and use it in our other APIs (including C#).

**Comment by stdcion** [comment]
we now support dxLink
