### ISSUE TITLE
Current target does not support the CPU features that are required by the image

### ISSUE THREAD

**Issue by veritacodex** [dxFeed/dxfeed-graal-net-api#75]
System: Ubuntu 24.04
IDE: VsCode

I am getting this exception when I run the very first line.

`using var endpoint = DXEndpoint.Create().Connect(address);`

Exception has occurred: CLR/DxFeed.Graal.Net.Native.ErrorHandling.GraalException
An exception of type 'DxFeed.Graal.Net.Native.ErrorHandling.GraalException' occurred in System.Private.CoreLib.dll but was not handled in user code: '**_Current target does not support the CPU features that are required by the image._**'
   at DxFeed.Graal.Net.Native.ErrorHandling.ErrorCheck.ThrowGraalException(GraalErrorCode errorCode)
   at DxFeed.Graal.Net.Native.ErrorHandling.ErrorCheck.SafeCall(GraalErrorCode result)
   at DxFeed.Graal.Net.Native.Graal.Isolate.CreateIsolate()
   at System.Lazy1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy1.CreateValue()
   at DxFeed.Graal.Net.Native.Graal.Isolate.get_Instance()
   at DxFeed.Graal.Net.Native.Graal.IsolateThread.get_CurrentThread()
   at DxFeed.Graal.Net.Native.Interop.JavaHandle.get_CurrentThread()
   at DxFeed.Graal.Net.Native.Endpoint.BuilderHandle.Create()
   at DxFeed.Graal.Net.Native.Endpoint.DXEndpointWrapper.BuilderWrapper..ctor()
   at DxFeed.Graal.Net.Api.DXEndpoint.Builder.Build()
   at DxFeed.Graal.Net.Api.DXEndpoint.Create(Role role)
   at DxFeed.Graal.Net.Api.DXEndpoint.Create()

Any ideas on how to fix it?

**Comment by stdcion** [comment]
Hello @veritacodex!

Please try running our compiled [DxFeed Tools](https://github.com/dxFeed/dxfeed-graal-net-api/releases/download/2.4.0/DxFeed.Graal.Net.Tools-linux-x64-2.4.0.zip) make sure they work:

`./DxFeed.Graal.Net.Tools connect demo.dxfeed.com:7300 Quote AAPL`

Expected result:
```
I 240805 104837.260 [main] QDFactory - Using QDS-3.333+file-UNKNOWN, (C) Devexperts
I 240805 104837.284 [main] QDFactory - Using scheme com.dxfeed.scheme.DXScheme ooBTbsbYYwm70q0JjvkdHCP_kOumBCRyr0mI4XOGw6c
I 240805 104837.292 [main] MARS - Started time synchronization tracker using multicast 239.192.51.45:5145 with XvuXN
I 240805 104837.296 [main] MARS - Started JVM self-monitoring
I 240805 104837.297 [main] MonitoredQDEndpoint - ConnectTool with collectors [Ticker, Stream, History]
I 240805 104837.301 [main] DXEndpointImpl - ConnectTool DXEndpoint with dxfeed.wildcard.enable=true
I 240805 104837.347 [main] ClientSocket-Distributor - Starting ClientSocketConnector to demo.dxfeed.com:7300
I 240805 104837.348 [demo.dxfeed.com:7300-Reader] ClientSocket-Distributor - Resolving IPs for demo.dxfeed.com
I 240805 104837.353 [demo.dxfeed.com:7300-Reader] ClientSocket-Distributor - Connecting to 208.93.103.170:7300
I 240805 104837.493 [demo.dxfeed.com:7300-Reader] ClientSocket-Distributor - Connected to 208.93.103.170:7300
I 240805 104837.633 [demo.dxfeed.com:7300-Reader] MessageAdapter - Distributor received protocol descriptor multiplexor@yysMU [type=qtp, version=QDS-3.327, opt=hs, mars.root=mdd.demo-amazon.multiplexor-demo1] sending [TICKER, STREAM, HISTORY, DATA] from 208.93.103.170
Quote{AAPL, eventTime=0, time=20240805-100000.000, timeNanoPart=0, sequence=0, bidTime=20240805-100000.000, bidExchange=P, bidPrice=219.26, bidSize=NaN, askTime=20240805-100000.000, askExchange=Q, askPrice=219.28, askSize=NaN}
```

Additionally, could you please provide the following information to help us better understand your environment?
1. The version of .NET you are using.
2. The model of your CPU.

Best regards,
dxFeed APIs Team

**Comment by veritacodex** [comment]
Hi, thanks for that.

The output of the tool. throws the same exception:

`
$ ./DxFeed.Graal.Net.Tools connect demo.dxfeed.com:7300 Quote AAPL
Unhandled exception. DxFeed.Graal.Net.Native.ErrorHandling.GraalException: Current target does not support the CPU features that are required by the image.
   at DxFeed.Graal.Net.Native.ErrorHandling.ErrorCheck.ThrowGraalException(GraalErrorCode errorCode)
   at DxFeed.Graal.Net.Native.ErrorHandling.ErrorCheck.SafeCall(GraalErrorCode result)
   at DxFeed.Graal.Net.Native.Graal.Isolate.CreateIsolate()
   at System.Lazy1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy1.CreateValue()
   at DxFeed.Graal.Net.Native.Graal.Isolate.get_Instance()
   at DxFeed.Graal.Net.Native.Graal.IsolateThread.get_CurrentThread()
   at DxFeed.Graal.Net.Native.Graal.Isolate.get_CurrentThread()
   at DxFeed.Graal.Net.SystemProperty.SetProperty(String key, String value)
   at DxFeed.Graal.Net.Tools.Program.Main(String[] args)
Aborted (core dumped)
`

**_.NET version:_** 8.0.107
_**CPU:**_ Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

**Comment by stdcion** [comment]
Looks like we found the root cause, Try using version 2.4.1 and first try running new [DxFeed Tools](https://github.com/dxFeed/dxfeed-graal-net-api/releases/download/2.4.1/DxFeed.Graal.Net.Tools-linux-x64-2.4.1.zip):

`./DxFeed.Graal.Net.Tools connect demo.dxfeed.com:7300 Quote AAPL`

**Comment by stdcion** [comment]
We have also added to the [Installation ](https://github.com/dxFeed/dxfeed-graal-net-api?tab=readme-ov-file#installation)section how to create a project for VSCode.

**Comment by veritacodex** [comment]
The new version works , as per output below:

./DxFeed.Graal.Net.Tools connect demo.dxfeed.com:7300 Quote AAPL
I 240805 131341.170 [main] QDFactory - Using QDS-3.333+file-UNKNOWN, (C) Devexperts
I 240805 131341.203 [main] QDFactory - Using scheme com.dxfeed.scheme.DXScheme ooBTbsbYYwm70q0JjvkdHCP_kOumBCRyr0mI4XOGw6c
I 240805 131341.213 [main] MARS - Started time synchronization tracker using multicast 239.192.51.45:5145 with lYJHk
I 240805 131341.218 [main] MARS - Started JVM self-monitoring
I 240805 131341.219 [main] MonitoredQDEndpoint - ConnectTool with collectors [Ticker, Stream, History]
I 240805 131341.224 [main] DXEndpointImpl - ConnectTool DXEndpoint with dxfeed.wildcard.enable=true
I 240805 131341.255 [main] ClientSocket-Distributor - Starting ClientSocketConnector to demo.dxfeed.com:7300
I 240805 131341.255 [demo.dxfeed.com:7300-Reader] ClientSocket-Distributor - Resolving IPs for demo.dxfeed.com
I 240805 131341.301 [demo.dxfeed.com:7300-Reader] ClientSocket-Distributor - Connecting to 208.93.103.170:7300
I 240805 131341.406 [demo.dxfeed.com:7300-Reader] ClientSocket-Distributor - Connected to 208.93.103.170:7300
I 240805 131341.513 [demo.dxfeed.com:7300-Reader] MessageAdapter - Distributor received protocol descriptor multiplexor@yysMU [type=qtp, version=QDS-3.327, opt=hs, mars.root=mdd.demo-amazon.multiplexor-demo1] sending [TICKER, STREAM, HISTORY, DATA] from 208.93.103.170
Quote{AAPL, eventTime=0, time=20240805-125839.000, timeNanoPart=0, sequence=0, bidTime=20240805-125838.000, bidExchange=P, bidPrice=203.25, bidSize=3, askTime=20240805-125839.000, askExchange=P, askPrice=203.5, askSize=2}
