### ISSUE TITLE
Option Chain Greeks

### ISSUE THREAD

**Issue by veritacodex** [dxFeed/dxfeed-graal-net-api#82]
Hi, I am able to retrieve the whole option chain for an expiration date without any problem. 
But I can't get any Greeks for those strikes. 

Code at: https://github.com/veritacodex/TastyTrade.Api.Client/blob/main/TastyTrade.Client.Examples/Program.cs

The broker provides a streaming symbol per strike and side (call/put). Using that streaming symbol with the Quote subscription retrieves Bid and Ask per strike and side nicely.

Would you have an example for retrieving greeks for those strikes? Ideally I would get a Greeks object the very same way I get the Quote one, so I can match strike and side on the option chain.

**Comment by stdcion** [comment]
Hi @veritacodex!

Yes, you can subscribe to Greeks just like you can subscribe to Quote, but note that you must use Option Symbol, not Underlying, to subscribe to Greeks ([dxFeed Symbol Guide](https://dxfeed.com/wp-content/uploads/2012/05/dxFeed_Symbol_Guide.pdf)), here's an example:

```csharp
    public static async Task Main(string[] args)
    {
        SystemProperty.SetProperty("dxfeed.experimental.dxlink.enable", "true");
        SystemProperty.SetProperty("scheme", "ext:opt:sysprops,resource:dxlink.xml");
        SystemProperty.SetProperty("dxfeed.address", "dxlink:wss://demo.dxfeed.com/dxlink-ws");

        var symbol = ".AAPL240920C270";
        var sub = DXFeed.GetInstance().CreateSubscription(typeof(Greeks));
        sub.AddEventListener(events =>
        {
            foreach (var greek in events)
            {
                Console.WriteLine(greek);
            }
        });
        sub.AddSymbols(symbol);

        await Task.Delay(Timeout.Infinite);
    }
```

Expected result:
```
I 240821 124036.910 [main] MARS - Started JVM self-monitoring
I 240821 124036.915 [main] MonitoredQDEndpoint - qdnet with collectors [Ticker, Stream, History]
I 240821 124036.996 [main] DXEndpointImpl - qdnet DXEndpoint with dxfeed.address=dxlink:wss://demo.dxfeed.com/dxlink-ws
I 240821 124037.074 [main] DxLinkClientWebSocket-Distributor - Starting DxLinkClientWebSocketConnector to wss://demo.dxfeed.com/dxlink-ws
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
I 240821 124037.204 [wss://demo.dxfeed.com/dxlink-ws-Writer] DxLinkClientWebSocket-Distributor - Connecting to wss://demo.dxfeed.com/dxlink-ws
I 240821 124038.320 [oioEventLoopGroup-2-1] DxLinkClientWebSocket-Distributor - Connected to wss://demo.dxfeed.com/dxlink-ws, host=demo.dxfeed.com/208.93.103.170:443, sec extensions=permessage-deflate
I 240821 124038.510 [oioEventLoopGroup-2-1] MessageAdapter - Distributor received protocol descriptor [type=dxlink, version=1.0-1.2.1-20240722-153442, keepaliveTimeout=60.0, acceptKeepaliveTimeout=60.0] sending [] from wss://demo.dxfeed.com/dxlink-ws
I 240821 124038.512 [oioEventLoopGroup-2-1] MessageAdapter - Distributor received protocol descriptor [type=dxlink, version=1.0-1.2.1-20240722-153442, keepaliveTimeout=60.0, acceptKeepaliveTimeout=60.0, authentication=] sending [] from wss://demo.dxfeed.com/dxlink-ws
Greeks{.AAPL240920C270, eventTime=0, eventFlags=0x0, time=20240821-122156.750, sequence=0, price=0.0463748709318702, volatility=0.250853890590944, delta=0.00865255264773237, gamma=0.001430145140553465, theta=-0.00632825504747365, rho=0.0015969192179374, vega=0.01536986281685444}

```

**Comment by stdcion** [comment]
> I have to use the DXEndpoint class in order to connect to the broker using an authentication token and I wonder if that is causing any difference.
 
No, there's no difference.

> Is there anything I can do to check that the feed I am using should return greeks?
> Could I run any test to double check that the feed from the broker is correct before contacting them?

Unfortunately, there isn't a reliable way for the end client to check if a symbol or market event is available to them. The dxLink endpoints do not publish a list of filters. However, if you are a Tastytrade Open API user, I can confirm that Greeks are not available. For questions about the availability of specific market events or symbols, you should contact your broker.

Best regards,
dxFeed APIs Team
